@call AutoCompleteTextBox-compile.cmd
@call BlockyPixel-compile.cmd
@call BreadcrumbPanel-compile.cmd
@call Card-compile.cmd
@call Grid-compile.cmd
@call Life-compile.cmd
@call Menu-compile.cmd
@call Pager-compile.cmd
@call SortableTable-compile.cmd
@call TabPanel-compile.cmd
@call ZebraFlexTable-compile.cmd
